# Generated by Django 3.2 on 2023-01-17 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StallholderApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('email', models.EmailField(max_length=155)),
                ('comapny_name', models.CharField(max_length=500)),
                ('product_type', models.TextField(max_length=1000)),
                ('date_submitted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Application Form',
                'verbose_name_plural': 'Application Forms',
                'ordering': ['-date_submitted'],
            },
        ),
    ]
