# Generated by Django 3.2 on 2022-12-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options'),
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwishlist',
            name='product',
        ),
        migrations.AddField(
            model_name='userwishlist',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.Product'),
        ),
    ]
